### ISSUE TITLE
g

### ISSUE THREAD

**Issue by PurplikDev** [lnxcz/gamesa-skola#4]
![pjedroO](https://user-images.githubusercontent.com/60230933/220850176-def75517-ef89-4cd1-9544-3f8f61d190f2.png)

**Comment by dfrnoch** [comment]
![ab67616d0000b273da47928c6d0a7bf414e73b56](https://user-images.githubusercontent.com/67194087/220940331-97e8a861-bff0-426d-86f5-65ead23aad52.jpeg)
